### ISSUE TITLE
examples/DSPDemo doesn't compile on Linux since version 5.2

### ISSUE THREAD

**Issue by 0joshuaolson1** [WeAreROLI/JUCE#292]
I don't have Clang, so this is definitely on gcc 7.2.0 (Ubuntu, x64):
```
examples/DSPDemo/Builds/LinuxMakefile$ make
Compiling ConvolutionDemo.cpp
Compiling FIRFilterDemo.cpp
Compiling GainDemo.cpp
Compiling IIRFilterDemo.cpp
Compiling OscillatorDemo.cpp
Compiling OverdriveDemo.cpp
Compiling SIMDRegisterDemo.cpp
In file included from ../../../../modules/juce_dsp/juce_dsp.h:255:0,
                 from ../../Source/Demos/../../JuceLibraryCode/JuceHeader.h:24,
                 from ../../Source/Demos/../DSPDemo.h:29,
                 from ../../Source/Demos/SIMDRegisterDemo.cpp:27:
../../../../modules/juce_dsp/processors/juce_IIRFilter.h: In instantiation of ‘void juce::dsp::IIR::Filter<SampleType>::reset() [with SampleType = juce::dsp::SIMDRegister<float>]’:
../../../../modules/juce_dsp/processors/juce_IIRFilter_Impl.h:48:10:   required from ‘juce::dsp::IIR::Filter<SampleType>::Filter(juce::dsp::IIR::Coefficients<typename juce::dsp::SampleTypeHelpers::ElementType<SampleType>::Type>*) [with SampleType = juce::dsp::SIMDRegister<float>; typename juce::dsp::SampleTypeHelpers::ElementType<SampleType>::Type = float]’
../../Source/Demos/SIMDRegisterDemo.cpp:40:73:   required from here
../../../../modules/juce_dsp/processors/juce_IIRFilter.h:91:41: error: no matching function for call to ‘juce::dsp::IIR::Filter<juce::dsp::SIMDRegister<float> >::reset(<brace-enclosed initializer list>)’
         void reset()            { reset ({}); }
                                   ~~~~~~^~~~
../../../../modules/juce_dsp/processors/juce_IIRFilter.h:91:14: note: candidate: void juce::dsp::IIR::Filter<SampleType>::reset() [with SampleType = juce::dsp::SIMDRegister<float>]
         void reset()            { reset ({}); }
              ^~~~~
../../../../modules/juce_dsp/processors/juce_IIRFilter.h:91:14: note:   candidate expects 0 arguments, 1 provided
In file included from ../../../../modules/juce_dsp/processors/juce_IIRFilter.h:288:0,
                 from ../../../../modules/juce_dsp/juce_dsp.h:255,
                 from ../../Source/Demos/../../JuceLibraryCode/JuceHeader.h:24,
                 from ../../Source/Demos/../DSPDemo.h:29,
                 from ../../Source/Demos/SIMDRegisterDemo.cpp:27:
../../../../modules/juce_dsp/processors/juce_IIRFilter_Impl.h:52:6: note: candidate: void juce::dsp::IIR::Filter<SampleType>::reset(SampleType) [with SampleType = juce::dsp::SIMDRegister<float>]
 void Filter<SampleType>::reset (SampleType resetToValue)
      ^~~~~~~~~~~~~~~~~~
../../../../modules/juce_dsp/processors/juce_IIRFilter_Impl.h:52:6: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘juce::dsp::SIMDRegister<float>’
Makefile:136: recipe for target 'build/intermediate/Debug/SIMDRegisterDemo_1f8435fb.o' failed
make: *** [build/intermediate/Debug/SIMDRegisterDemo_1f8435fb.o] Error 1
```
It worked on `master` before `develop` was merged in. It was broken on `develop` a few days ago too.

**Comment by hogliux** [comment]
Thanks for the report. This is now fixed on develop with commit 13d18e4.
